
package org.tempuri;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import org.datacontract.schemas._2004._07.efactoring_webservices.ArrayOfCesionDocumentoModelComprador;
import org.datacontract.schemas._2004._07.efactoring_webservices.ArrayOfCesionDocumentoReporteModel;
import org.datacontract.schemas._2004._07.efactoring_webservices.RespuestaModel;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IWsCompradores", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
    com.microsoft.schemas._2003._10.serialization.ObjectFactory.class,
    org.datacontract.schemas._2004._07.efactoring_webservices.ObjectFactory.class,
    org.tempuri.ObjectFactory.class
})
public interface IWsCompradores {


    /**
     * 
     * @param password
     * @param autorizacionId
     * @param usuarioId
     * @return
     *     returns org.datacontract.schemas._2004._07.efactoring_webservices.ArrayOfCesionDocumentoModelComprador
     */
    @WebMethod(operationName = "DescargarCesiones", action = "http://tempuri.org/IWsCompradores/DescargarCesiones")
    @WebResult(name = "DescargarCesionesResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "DescargarCesiones", targetNamespace = "http://tempuri.org/", className = "org.tempuri.DescargarCesiones")
    @ResponseWrapper(localName = "DescargarCesionesResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.DescargarCesionesResponse")
    public ArrayOfCesionDocumentoModelComprador descargarCesiones(
        @WebParam(name = "autorizacionId", targetNamespace = "http://tempuri.org/")
        Long autorizacionId,
        @WebParam(name = "usuarioId", targetNamespace = "http://tempuri.org/")
        String usuarioId,
        @WebParam(name = "password", targetNamespace = "http://tempuri.org/")
        String password);

    /**
     * 
     * @param lCesionDocumentoReporteModel
     * @param password
     * @param autorizacionId
     * @param usuarioId
     * @return
     *     returns org.datacontract.schemas._2004._07.efactoring_webservices.RespuestaModel
     */
    @WebMethod(operationName = "InformarCesionesProcesadas", action = "http://tempuri.org/IWsCompradores/InformarCesionesProcesadas")
    @WebResult(name = "InformarCesionesProcesadasResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "InformarCesionesProcesadas", targetNamespace = "http://tempuri.org/", className = "org.tempuri.InformarCesionesProcesadas")
    @ResponseWrapper(localName = "InformarCesionesProcesadasResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.InformarCesionesProcesadasResponse")
    public RespuestaModel informarCesionesProcesadas(
        @WebParam(name = "autorizacionId", targetNamespace = "http://tempuri.org/")
        Long autorizacionId,
        @WebParam(name = "usuarioId", targetNamespace = "http://tempuri.org/")
        String usuarioId,
        @WebParam(name = "password", targetNamespace = "http://tempuri.org/")
        String password,
        @WebParam(name = "lCesionDocumentoReporteModel", targetNamespace = "http://tempuri.org/")
        ArrayOfCesionDocumentoReporteModel lCesionDocumentoReporteModel);

    /**
     * 
     * @param fecha
     * @param password
     * @param bytes
     * @param autorizacionId
     * @param usuarioId
     * @param archivoProveedoresNombre
     * @return
     *     returns org.datacontract.schemas._2004._07.efactoring_webservices.RespuestaModel
     */
    @WebMethod(operationName = "CargaArchivoProveedores", action = "http://tempuri.org/IWsCompradores/CargaArchivoProveedores")
    @WebResult(name = "CargaArchivoProveedoresResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "CargaArchivoProveedores", targetNamespace = "http://tempuri.org/", className = "org.tempuri.CargaArchivoProveedores")
    @ResponseWrapper(localName = "CargaArchivoProveedoresResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.CargaArchivoProveedoresResponse")
    public RespuestaModel cargaArchivoProveedores(
        @WebParam(name = "autorizacionId", targetNamespace = "http://tempuri.org/")
        Long autorizacionId,
        @WebParam(name = "usuarioId", targetNamespace = "http://tempuri.org/")
        String usuarioId,
        @WebParam(name = "password", targetNamespace = "http://tempuri.org/")
        String password,
        @WebParam(name = "fecha", targetNamespace = "http://tempuri.org/")
        XMLGregorianCalendar fecha,
        @WebParam(name = "ArchivoProveedoresNombre", targetNamespace = "http://tempuri.org/")
        String archivoProveedoresNombre,
        @WebParam(name = "bytes", targetNamespace = "http://tempuri.org/")
        byte[] bytes);

    /**
     * 
     * @param fecha
     * @param archivoDocumentosNombre
     * @param password
     * @param bytes
     * @param autorizacionId
     * @param usuarioId
     * @return
     *     returns org.datacontract.schemas._2004._07.efactoring_webservices.RespuestaModel
     */
    @WebMethod(operationName = "CargaArchivoDocumentos", action = "http://tempuri.org/IWsCompradores/CargaArchivoDocumentos")
    @WebResult(name = "CargaArchivoDocumentosResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "CargaArchivoDocumentos", targetNamespace = "http://tempuri.org/", className = "org.tempuri.CargaArchivoDocumentos")
    @ResponseWrapper(localName = "CargaArchivoDocumentosResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.CargaArchivoDocumentosResponse")
    public RespuestaModel cargaArchivoDocumentos(
        @WebParam(name = "autorizacionId", targetNamespace = "http://tempuri.org/")
        Long autorizacionId,
        @WebParam(name = "usuarioId", targetNamespace = "http://tempuri.org/")
        String usuarioId,
        @WebParam(name = "password", targetNamespace = "http://tempuri.org/")
        String password,
        @WebParam(name = "fecha", targetNamespace = "http://tempuri.org/")
        XMLGregorianCalendar fecha,
        @WebParam(name = "ArchivoDocumentosNombre", targetNamespace = "http://tempuri.org/")
        String archivoDocumentosNombre,
        @WebParam(name = "bytes", targetNamespace = "http://tempuri.org/")
        byte[] bytes);

    /**
     * 
     * @param archivoDetalleNombre
     * @param fecha
     * @param password
     * @param archivoEncabezadoNombre
     * @param archivoDetalleBytes
     * @param autorizacionId
     * @param usuarioId
     * @param archivoEncabezadoBytes
     * @return
     *     returns org.datacontract.schemas._2004._07.efactoring_webservices.RespuestaModel
     */
    @WebMethod(operationName = "CargaArchivoPagos", action = "http://tempuri.org/IWsCompradores/CargaArchivoPagos")
    @WebResult(name = "CargaArchivoPagosResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "CargaArchivoPagos", targetNamespace = "http://tempuri.org/", className = "org.tempuri.CargaArchivoPagos")
    @ResponseWrapper(localName = "CargaArchivoPagosResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.CargaArchivoPagosResponse")
    public RespuestaModel cargaArchivoPagos(
        @WebParam(name = "autorizacionId", targetNamespace = "http://tempuri.org/")
        Long autorizacionId,
        @WebParam(name = "usuarioId", targetNamespace = "http://tempuri.org/")
        String usuarioId,
        @WebParam(name = "password", targetNamespace = "http://tempuri.org/")
        String password,
        @WebParam(name = "fecha", targetNamespace = "http://tempuri.org/")
        XMLGregorianCalendar fecha,
        @WebParam(name = "ArchivoEncabezadoNombre", targetNamespace = "http://tempuri.org/")
        String archivoEncabezadoNombre,
        @WebParam(name = "ArchivoEncabezadoBytes", targetNamespace = "http://tempuri.org/")
        byte[] archivoEncabezadoBytes,
        @WebParam(name = "ArchivoDetalleNombre", targetNamespace = "http://tempuri.org/")
        String archivoDetalleNombre,
        @WebParam(name = "ArchivoDetalleBytes", targetNamespace = "http://tempuri.org/")
        byte[] archivoDetalleBytes);

    /**
     * 
     * @param fecha
     * @param archivoDocumentosNombre
     * @param password
     * @param bytes
     * @param autorizacionId
     * @param usuarioId
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "CargaPrueba", action = "http://tempuri.org/IWsCompradores/CargaPrueba")
    @WebResult(name = "CargaPruebaResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "CargaPrueba", targetNamespace = "http://tempuri.org/", className = "org.tempuri.CargaPrueba")
    @ResponseWrapper(localName = "CargaPruebaResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.CargaPruebaResponse")
    public String cargaPrueba(
        @WebParam(name = "autorizacionId", targetNamespace = "http://tempuri.org/")
        Long autorizacionId,
        @WebParam(name = "usuarioId", targetNamespace = "http://tempuri.org/")
        String usuarioId,
        @WebParam(name = "password", targetNamespace = "http://tempuri.org/")
        String password,
        @WebParam(name = "fecha", targetNamespace = "http://tempuri.org/")
        XMLGregorianCalendar fecha,
        @WebParam(name = "ArchivoDocumentosNombre", targetNamespace = "http://tempuri.org/")
        String archivoDocumentosNombre,
        @WebParam(name = "bytes", targetNamespace = "http://tempuri.org/")
        byte[] bytes);

}
