
package org.tempuri;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "WsCompradores", targetNamespace = "http://tempuri.org/", wsdlLocation = "https://www.linkproveedores.com:8085/WsCompradores.svc?singleWsdl")
public class WsCompradores
    extends Service
{

    private final static URL WSCOMPRADORES_WSDL_LOCATION;
    private final static WebServiceException WSCOMPRADORES_EXCEPTION;
    private final static QName WSCOMPRADORES_QNAME = new QName("http://tempuri.org/", "WsCompradores");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://www.linkproveedores.com:8085/WsCompradores.svc?singleWsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        WSCOMPRADORES_WSDL_LOCATION = url;
        WSCOMPRADORES_EXCEPTION = e;
    }

    public WsCompradores() {
        super(__getWsdlLocation(), WSCOMPRADORES_QNAME);
    }

    public WsCompradores(WebServiceFeature... features) {
        super(__getWsdlLocation(), WSCOMPRADORES_QNAME, features);
    }

    public WsCompradores(URL wsdlLocation) {
        super(wsdlLocation, WSCOMPRADORES_QNAME);
    }

    public WsCompradores(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, WSCOMPRADORES_QNAME, features);
    }

    public WsCompradores(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WsCompradores(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns IWsCompradores
     */
    @WebEndpoint(name = "wsHttpEndpoint")
    public IWsCompradores getWsHttpEndpoint() {
        return super.getPort(new QName("http://tempuri.org/", "wsHttpEndpoint"), IWsCompradores.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IWsCompradores
     */
    @WebEndpoint(name = "wsHttpEndpoint")
    public IWsCompradores getWsHttpEndpoint(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/", "wsHttpEndpoint"), IWsCompradores.class, features);
    }

    private static URL __getWsdlLocation() {
        if (WSCOMPRADORES_EXCEPTION!= null) {
            throw WSCOMPRADORES_EXCEPTION;
        }
        return WSCOMPRADORES_WSDL_LOCATION;
    }

}
