
package com.estrategit.curso.bo;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Calculadora", targetNamespace = "http://bo.curso.estrategit.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Calculadora {


    /**
     * 
     * @param sumando1
     * @param sumando2
     * @return
     *     returns java.lang.Double
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sumar", targetNamespace = "http://bo.curso.estrategit.com/", className = "com.estrategit.curso.bo.Sumar")
    @ResponseWrapper(localName = "sumarResponse", targetNamespace = "http://bo.curso.estrategit.com/", className = "com.estrategit.curso.bo.SumarResponse")
    public Double sumar(
        @WebParam(name = "sumando1", targetNamespace = "")
        Double sumando1,
        @WebParam(name = "sumando2", targetNamespace = "")
        Double sumando2);

}
