
package com.estrategit.curso.bo;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "CalculadoraService", targetNamespace = "http://bo.curso.estrategit.com/", wsdlLocation = "http://localhost:8080/taller-servlet/Calculadora?wsdl")
public class CalculadoraService
    extends Service
{

    private final static URL CALCULADORASERVICE_WSDL_LOCATION;
    private final static WebServiceException CALCULADORASERVICE_EXCEPTION;
    private final static QName CALCULADORASERVICE_QNAME = new QName("http://bo.curso.estrategit.com/", "CalculadoraService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/taller-servlet/Calculadora?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CALCULADORASERVICE_WSDL_LOCATION = url;
        CALCULADORASERVICE_EXCEPTION = e;
    }

    public CalculadoraService() {
        super(__getWsdlLocation(), CALCULADORASERVICE_QNAME);
    }

    public CalculadoraService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CALCULADORASERVICE_QNAME, features);
    }

    public CalculadoraService(URL wsdlLocation) {
        super(wsdlLocation, CALCULADORASERVICE_QNAME);
    }

    public CalculadoraService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CALCULADORASERVICE_QNAME, features);
    }

    public CalculadoraService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CalculadoraService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Calculadora
     */
    @WebEndpoint(name = "CalculadoraPort")
    public Calculadora getCalculadoraPort() {
        return super.getPort(new QName("http://bo.curso.estrategit.com/", "CalculadoraPort"), Calculadora.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Calculadora
     */
    @WebEndpoint(name = "CalculadoraPort")
    public Calculadora getCalculadoraPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://bo.curso.estrategit.com/", "CalculadoraPort"), Calculadora.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CALCULADORASERVICE_EXCEPTION!= null) {
            throw CALCULADORASERVICE_EXCEPTION;
        }
        return CALCULADORASERVICE_WSDL_LOCATION;
    }

}
